### ISSUE TITLE
Nil panic, no method _, internal error

### ISSUE THREAD

**Issue by karalabe** [stamblerre/gocode#32]
I created a repro to keep things simple: https://github.com/karalabe/gocodekiller. This single dependency more or less murders gocode in wondrous ways:

```
internal error: error "context canceled" (*errors.errorString) without position
```

```
error in package github.com/karalabe/gocodekiller: /work/mod/github.com/ipsn/gocodekiller/main.go:11:8:node._ undefined (type *core.IpfsNode has no field or method _)
```

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 7064 [running]:
runtime/debug.Stack(0x49, 0x0, 0x0)
	/opt/google/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/opt/google/go/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc013eec960)
	/work/src/github.com/stamblerre/gocode/server.go:80 +0xad
panic(0x8a06e0, 0xd02c00)
	/opt/google/go/src/runtime/panic.go:522 +0x1b5
golang.org/x/tools/go/packages.goListDriver(0xc00014f2c8, 0xc016c0a5a0, 0x1, 0x1, 0x45, 0x10, 0xc00014f2c0)
	/work/src/golang.org/x/tools/go/packages/golist.go:195 +0x5e4
golang.org/x/tools/go/packages.defaultDriver(0xc00014f2c8, 0xc016c0a5a0, 0x1, 0x1, 0xc0071a8000, 0xc0046f3500, 0x34)
	/work/src/golang.org/x/tools/go/packages/packages.go:188 +0x68
golang.org/x/tools/go/packages.Load(0xc002c157e8, 0xc016c0a5a0, 0x1, 0x1, 0x1, 0xc00c6979c0, 0x34, 0x1, 0xc013e32860)
	/work/src/golang.org/x/tools/go/packages/packages.go:173 +0x6f
github.com/stamblerre/gocode/internal/suggest.(*Config).analyzePackage(0xc002c15b08, 0xc01206c840, 0x2f, 0xc0001b0a00, 0x14bc, 0x14bc, 0xe6f, 0x0, 0x0, 0x13, ...)
	/work/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:183 +0x587
github.com/stamblerre/gocode/internal/suggest.(*Config).Suggest(0xc002c15b08, 0xc01206c840, 0x2f, 0xc0001b0a00, 0x14bc, 0x14bc, 0xe6f, 0x40a0ac, 0xc000012000, 0x8b1f60, ...)
	/work/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:59 +0x9a
main.(*Server).AutoComplete(0xc0000acbc0, 0x9d5500, 0xc017ec3bc0, 0xc017ec38c0, 0xc013eec960, 0x0, 0x0)
	/work/src/github.com/stamblerre/gocode/server.go:127 +0x250
reflect.Value.call(0xc000122400, 0xc0000b6578, 0x13, 0x92096f, 0x4, 0xc000aa2ef8, 0x4, 0x4, 0xc000cd6690, 0x10, ...)
	/opt/google/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc000122400, 0xc0000b6578, 0x13, 0xc000cd66f8, 0x4, 0x4, 0x503e53, 0xc00db79500, 0x28)
	/opt/google/go/src/reflect/value.go:308 +0xa4
github.com/stamblerre/gocode/vendor/github.com/keegancsmith/rpc.(*service).call(0xc0000bba80, 0xc000136000, 0xc017d7ef30, 0xc017053000, 0xc017d7ef60, 0xc000122480, 0xc00015a0a0, 0x862de0, 0xc017ec38c0, 0x16, ...)
	/work/src/github.com/stamblerre/gocode/vendor/github.com/keegancsmith/rpc/server.go:419 +0x288
created by github.com/stamblerre/gocode/vendor/github.com/keegancsmith/rpc.(*Server).ServeCodec
	/work/src/github.com/stamblerre/gocode/vendor/github.com/keegancsmith/rpc/server.go:517 +0x498
```

**Comment by stamblerre** [comment]
Sorry for not getting back to you earlier. I just tried your repro, and I don't see the failure, so I believe it must have been fixed on the go/packages side. There have been a number of updates to the go/packages library since this issue was filed, so I imagine that this nil pointer no longer exists. Please open an issue on the [Go issue tracker](https://github.com/golang/go/issues/new), if you do see another nil pointer in the go/packages code.

**Comment by stamblerre** [comment]
Closing this issue, as the current recommendation for autocompletion is to use [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md).
