### ISSUE TITLE
Found 1 candidates PANIC PANIC PANIC

### ISSUE THREAD

**Issue by st1971** [stamblerre/gocode#7]
Trying to get VSCode autocomplete working with go modules, only candidate returned is PANIC.

VSCode installs this module as gocode-gomod 

If I execute:
`gocode-gomod -builtin -debug -source -in ./hello.go autocomplete 12`

I get the result
```
Found 1 candidates:
  PANIC PANIC PANIC
2018/10/14 12:13:42 Elapsed duration: 1.641874ms
```
Content of the hello.go file is
```
package main

import (
	"fmt"

	"rsc.io/quote"
)

func main() {
	fmt.Println(quote.Hello())
	quote.Hello()
	fmt.


}
```
To isolate if this is an issue with the way that VSCode has installed / compiled this module I have downloaded / compiled / installed using a clean GOPATH, the same result with the same source file is seen.

I have included environment information which is below, if there is any other information that can help let me know or if you would like me to try anything.

Kind Regards,
Steve

**go version output**
``
go version go1.11.1 linux/amd64
``
**go env output**
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/steve/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/steve/Development/tmpgo"
GOPROXY=""
GORACE=""
GOROOT="/home/steve/.local/opt/go"
GOTMPDIR=""
GOTOOLDIR="/home/steve/.local/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/steve/Development/go-module/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build828722581=/tmp/go-build -gno-record-gcc-switches"
```
**OS**
`Fedora 28 with a 4.18.12-200.fc28.x86_64 kernel`

**Comment by st1971** [comment]
Have just run server side debug on this and the output is below

```
2018/10/14 12:41:55 Got autocompletion request for '/home/steve/Development/go-module/hello.go'
2018/10/14 12:41:55 Cursor at: 112
2018/10/14 12:41:55 -------------------------------------------------------
package main

import (
	"fmt"

	"rsc.io/quote"
)

func main() {
	fmt.Println(quote.Hello())
	quote.Hello()
	fmt.#


}
2018/10/14 12:41:55 -------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 26 [running]:
runtime/debug.Stack(0xb, 0xc0001cd438, 0x1)
	/home/steve/.local/opt/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/home/steve/.local/opt/go/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc00014fae0)
	/home/steve/Development/go/primary/src/github.com/stamblerre/gocode/server.go:78 +0x94
panic(0x84bfc0, 0xc36c20)
	/home/steve/.local/opt/go/src/runtime/panic.go:513 +0x1b9
github.com/stamblerre/gocode/internal/suggest.(*Config).analyzePackage(0xc0001cda98, 0xc0001a0960, 0x2a, 0xc000186500, 0x75, 0x75, 0x70, 0x0, 0x0, 0xd0, ...)
	/home/steve/Development/go/primary/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:128 +0x251
github.com/stamblerre/gocode/internal/suggest.(*Config).Suggest(0xc0001cda98, 0xc0001a0960, 0x2a, 0xc000186500, 0x75, 0x75, 0x70, 0x4ae642, 0xc469e0, 0x86a560, ...)
	/home/steve/Development/go/primary/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:55 +0xb5
main.(*Server).AutoComplete(0xc649b0, 0xc0001378c0, 0xc00014fae0, 0x0, 0x0)
	/home/steve/Development/go/primary/src/github.com/stamblerre/gocode/server.go:104 +0x138
reflect.Value.call(0xc000176360, 0xc000154068, 0x13, 0x8c61ed, 0x4, 0xc00020af18, 0x3, 0x3, 0xc000124040, 0x823fc0, ...)
	/home/steve/.local/opt/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc000176360, 0xc000154068, 0x13, 0xc0001e8718, 0x3, 0x3, 0x895da0, 0x8a6401, 0xc0001377c0)
	/home/steve/.local/opt/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc000136500, 0xc0000ac320, 0xc00013a838, 0xc00013a850, 0xc000158280, 0xc00014e240, 0x810140, 0xc0001378c0, 0x16, 0x810100, ...)
	/home/steve/.local/opt/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/home/steve/.local/opt/go/src/net/rpc/server.go:481 +0x47e

```

**Comment by stamblerre** [comment]
I will investigate this ASAP, but this is probably a result of some changes I pulled in from upstream on Friday. For now, I'd recommend syncing to https://github.com/stamblerre/gocode/commit/32181df22c3e74ff09d4e12f1276ab3beea37659. I'm really sorry about this, hopefully will have it fixed ASAP.

**Comment by stamblerre** [comment]
Should be fixed now, I messed up a line when merging things. Sorry about that, and thank you for pointing it out.

**Comment by st1971** [comment]
Just test and it's working great now, thank you
